config/routes.rb
Objar::Application.routes.draw do
  devise_for :users
  resources :users
  resources :ar_objects
  
  root :to => 'static_pages#home'
  
  match '/new_3d', to: 'ar_objects#new_3d'
  match '/new_image', to: 'ar_objects#new_image'
  match '/new_ibniz', to: 'ar_objects#new_ibniz'

  

end

app/models/ar_3d.rb
class Ar3d < ActiveRecord::Base
  attr_accessible :ar_object_id, :fragmentshader, :geometry, :texture_id, :use_shader, :use_texture, :vertexshader
  belongs_to :ar_object
  validates :ar_object_id, presence: true
end

app/models/ar_object.rb
class ArObject < ActiveRecord::Base
  attr_accessible :description, :marker_id, :pos_x, :pos_y, :pos_z, :rot_x, :rot_y, :rot_z, :size_x, :size_y, :size_z, :title, :user_id
  belongs_to :user
  validates :user_id, presence: true

end

app/models/gps.rb
class Gps < ActiveRecord::Base
  attr_accessible :ar_object_id, :latitude, :longitude
  belongs_to :ar_object
  validates :ar_object_id, presence: true
end

app/models/marker.rb
class Marker < ActiveRecord::Base
  attr_accessible :imagename, :name, :public, :user_id
  belongs_to :user
  validates :user_id, presence: true
end

app/models/texture.rb
class Texture < ActiveRecord::Base
  attr_accessible :filename
  belongs_to :ar_3d
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :ar_objects
  has_many :markers
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ar_objects_controller.rb
class ArObjectsController < ApplicationController
	
	def new
		if user_signed_in?
			  @ar_object  = current_user.ar_objects.build
		end
  	end
	
	def new_3d
		if user_signed_in?
			  @ar_object  = current_user.ar_objects.build
			  @ar_object_3d = @ar_object.ar3d.build			
		end
	end
	
	
	def create
		@ar_object = current_user.ar_objects.build(params[:ar_object])
		if @ar_object.save
		  flash[:success] = "Arobject created!"
		  redirect_to root_url
		else
		 #@feed_items = []
		 # render 'static_pages/home'
		end
	end
	
	def index
		@ar_objects = current_user.ar_objects
	end
	
	def show
		@ar_object = current_user.ar_objects.find(params[:id])
	end
	
	def destroy
		@ar_object = ArObject.find(params[:id])
		@ar_object.destroy
		redirect_to root_url
  	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

 def home
	
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

def index
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end
	
	def show
		@user = User.find(params[:id])
		@ar_objects = @user.ar_objects.all #paginate(page: params[:page], :per_page => 8)	
	end
	
	def ar_objects
		@user = User.find(params[:id])
		@ar_objects = @user.ar_objects.all #paginate(page: params[:page], :per_page => 8)	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ar_object_helper.rb
module ArObjectHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/ar_objects/index.html.erb
<ul>
	<% current_user.ar_objects.each do |o| %>
	<li>    
	<%=  o.id   %>
	<%=  o.title  %>
		<% if user_signed_in? %>
	<%= link_to "delete", ar_objects_path, method: :delete,
								 confirm: "You sure?",
								 title: o.title %>
			<% end %>
	</li>
	<% end %>
</ul>

app/views/ar_objects/new.html.erb
<h1>Create Objects:</h1>
	
	<ul class='new_ar_objects'>
		<li><%= link_to 'New 3d Experience', new_3d_path, class: 'button' %></li>
		<li><%= link_to 'New Virtual Image', new_image_path, class: 'button' %></li>
		<li><%= link_to 'New Audiovisual Ibniz Demo', new_ibniz_path, class: 'button' %></li>
	</ul>
			
	
	
	
	
	<%= form_for @ar_object do |f| %>
	
	  <%= f.label :title %>
	  <%= f.text_field :title  %>
	  <%= f.label :description %>
	  <%= f.text_field :description %>
	  <%= f.label :pos_x %>
	  <%= f.text_field :pos_x,:value => '0' %>
	  <%= f.label :pos_y %>
	  <%= f.text_field :pos_y,:value => '0' %>
	  <%= f.label :pos_z %>
	  <%= f.text_field :pos_z,:value => '0' %>
	  <%= f.label :size_x %>
	  <%= f.text_field :size_x,:value => '1' %>
	  <%= f.label :size_y %>
	  <%= f.text_field :size_y,:value => '1' %>
	  <%= f.label :size_z %>
	  <%= f.text_field :size_z,:value => '1' %>
	  <%= f.label :rot_x %>
	  <%= f.text_field :rot_x,:value => '0' %> 
	  <%= f.label :rot_y %>
	  <%= f.text_field :rot_y,:value => '0' %>
	  <%= f.label :rot_z %>
	  <%= f.text_field :rot_z,:value => '0' %>
	  
	  
	  <%= f.submit "Create", class:'btn' %>
	<% end %>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
 
 <div class="container">
		
	<%= link_to "Objar Storage", root_path, class:'brand' %>
	
		<ul class="nav">
	<% if user_signed_in? %>
	
 		
		<li class="divider-vertical"></li>
		 <li><%= link_to 'New Object', new_ar_object_path%></li>
		 <li class="divider-vertical"></li>
 		 <li><%= link_to 'Edit profile', edit_user_registration_path%></li>
		 <li class="divider-vertical"></li>
  		<li><%= link_to "Logout", destroy_user_session_path, method: :delete%></li>
		<li class="divider-vertical"></li>
		<li class="btn"> Logged in as <%= current_user.email %></li>
  
	<% else %>
  		<li><%= link_to "Sign up", new_user_registration_path%></li>
		<li class="divider-vertical"></li>
  		<li><%= link_to "Login", new_user_session_path%></li>
	<% end %>
	
	</ul>
	</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Objar</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

    <%= render 'layouts/header' %>

  <div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
  
</body>
</html>

app/views/static_pages/_ar_objects.html.erb
<ul class='nav nav-tabs nav-stacked arobjects'>
	<% current_user.ar_objects.each do |o| %>
	<li>    
	<%=  o.id   %>
	<%=  o.title  %>
		<% if user_signed_in? %>
		

	<%= link_to "delete", o, method: :delete, confirm: "You sure?", title: o.title %>
			<% end %>
	</li>
	<% end %>
</ul>

app/views/static_pages/home.html.erb
<% if user_signed_in? %>
		
	<h1>My Objects:</h1>
	<%= render 'ar_objects' %>
	
<% end %>

app/views/user/index.html.erb
YO!

app/views/users/index.html.erb
<h1> All Users </h1> 

<% @users.each do |user| %>
<%= user.email %> 
<% end %>